working_directory = "/Users/tihav/source"
live_config_reload = true

[window]
dimensions = { columns = 140, lines = 90 }
position = { x = 50, y = 200 }
padding = { x = 12, y = 32 }
blur = true
opacity = 0.9
decorations = "Transparent"

[font]
normal = { family = "ZedMono NF", style = "Regular" }
size = 14

[selection]
save_to_clipboard = true
