# https://taskfile.dev

version: "3"

tasks:

  biome:
    desc: Copy biome config to cwd
    silent: true
    dir: "/{{.USER_WORKING_DIR}}"
    cmds:
      - cp $CONFIGS_DIR/format/biome.json ./biome.json

  rust:
    desc: Copy rustfmt config to cwd
    silent: true
    dir: "/{{.USER_WORKING_DIR}}"
    cmds:
      - cp $CONFIGS_DIR/format/rustfmt.toml ./rustfmt.toml
