# https://taskfile.dev

version: "3"

tasks:
  init:
    desc: Create new project structure in directory
    silent: true
    dir: "/{{.USER_WORKING_DIR}}"
    preconditions:
      - sh: '[ "$(ls -A .)" ] && exit 1 || exit 0'
        msg: "Directory is not empty {{.USER_WORKING_DIR}}"
    cmds:
      - git init
      - echo "# " >> README.md
      - echo "node_modules" >> .gitignore
      - echo "dist" >> .gitignore
      - echo "!.mise.toml" >> .gitignore
      - mise use task
      - task --init
      - mkdir apps
      - mkdir src
      - npm init -y
      - git add --all
      - git commit -m "Initial commit"

  biome:
    desc: Copy biome config to cwd
    silent: true
    dir: "/{{.USER_WORKING_DIR}}"
    cmds:
      - cp $CONFIGS_DIR/format/biome.json ./biome.json

  rust:
    desc: Copy rustfmt config to cwd
    silent: true
    dir: "/{{.USER_WORKING_DIR}}"
    cmds:
      - cp $CONFIGS_DIR/format/rustfmt.toml ./rustfmt.toml
