# https://taskfile.dev

version: "3"

includes:
  project:
    taskfile: ~/configs/task/project.yml
    aliases: ["p"]

tasks:
  clean:
    desc: Reset repository files
    dir: "{{.USER_WORKING_DIR}}"
    prompt: Do you really want to reset the repository?
    cmds:
      - git add --all
      - git stash
      - git clean -xdf .
      - git pop

  up:
    desc: Run docker compose up
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - docker compose up

  down:
    desc: Run docker compose down
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - docker compose down

  dev:
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - npm run dev

  vite:
    desc: vite dev
    silent: true
    dir: "{{.USER_WORKING_DIR}}"
    cmds:
      - npx vite -c vite.config.ts {{.args}}
