#!/usr/bin/env bash

export CONFIGS_DIR=~/configs
export PATH="$PATH:$HOME/bin"
export MISE_INSTALL_PATH=$HOME/bin/mise

function explain() {
    echo ""
    echo "#######################################################"
    echo ""
    echo "Installation complete. Open a new Terminal."
    echo ""
    echo "To sync config to the latest commit run: sync"
    echo ""
    echo "#######################################################"
    echo ""
}

git clone https://github.com/luckydye/configs.git ${CONFIGS_DIR} || exit 1

# install task
sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b $HOME/bin || exit 1

echo "# luckydye configs" >> ~/.zshrc || exit 1
echo "source $CONFIGS_DIR/.zshrc" >> ~/.zshrc || exit 1
source $CONFIGS_DIR/.zshrc || exit 1

task -t $CONFIGS_DIR/setup.yml || exit 1

explain
