#!/usr/bin/env bash

export CONFIGS_DIR=~/configs
export PATH="$PATH:$HOME/bin"
export MISE_INSTALL_PATH=$HOME/bin/mise

function explain() {
    echo ""
    echo "#######################################################"
    echo ""
    echo "Installation complete. Open a new Terminal."
    echo ""
    echo "To sync config to the latest commit run: sync"
    echo ""
    echo "#######################################################"
    echo ""
}

function install_zshrc() {
  echo "# luckydye configs" >> ~/.zshrc || exit 1
  echo "source $CONFIGS_DIR/.zshrc" >> ~/.zshrc || exit 1
}

git clone https://github.com/luckydye/configs.git ${CONFIGS_DIR}

grep -Fxq "# luckydye configs" ~/.zshrc || install_zshrc

# install mise
curl https://mise.run | sh

mise install -y || true

source $CONFIGS_DIR/.zshrc || exit 1
$CONFIGS_DIR/setup || exit 1

explain
