source $CONFIGS_DIR/env 2>/dev/null

export CONFIGS_DIR=~/configs

export PATH="$PATH:$HOME/bin"

export GPG_TTY=$(tty)

export EDITOR=zed

export MISE_EXPERIMENTAL=true
export MISE_TRUSTED_CONFIG_PATHS=~$HOME/.config/mise/config.toml

export FZF_DEFAULT_COMMAND='fd --type f --strip-cwd-prefix'
export FZF_DEFAULT_OPTS='--height=100% --info=inline --preview-window="up,70%,border-horizontal"'

export GIT_LFS_SKIP_SMUDGE=1

export KEY_S3_ACCESS_KEY=$STORAGE_ACCESS_KEY_ID
export KEY_S3_SECRET_KEY=$STORAGE_ACCESS_KEY_SECRET

export RCLONE_CONFIG_STORAGE_TYPE=s3
export RCLONE_CONFIG_STORAGE_PROVIDER=Minio
export RCLONE_CONFIG_STORAGE_REGION=$STORAGE_REGION
export RCLONE_CONFIG_STORAGE_ENDPOINT=$STORAGE_ENDPOINT
export RCLONE_CONFIG_STORAGE_ACCESS_KEY_ID=$STORAGE_ACCESS_KEY_ID
export RCLONE_CONFIG_STORAGE_SECRET_ACCESS_KEY=$STORAGE_ACCESS_KEY_SECRET
