# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
gui:
  showRandomTip: false
  showBottomLine: false
  branchColors:
    'main': '#11aaff'
    'develop': '#11aaff'

  authorColors:
    'Tim Havlicek': '#11aaff'
    '*': '#ff0000'

git:
  branchLogCmd: "git log --graph --author-date-order --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' {{branchName}}"
  disableForcePushing: true
  notARepository: 'skip'

  commitPrefixes:
    greentrails:
      pattern: "^(feat|fix).*\\/(\\w+)"
      replace: '$1(frontend): $2'


