# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json

git:
  commitPrefix: "feat(frontend): "
  branchLogCmd: "git log --graph --author-date-order --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)' --all"


