# https://taskfile.dev

version: '3'

tasks:

  init:
    desc: Create new project structure in directory
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - sh: '[ "$(ls -A .)" ] && exit 1 || exit 0'
        msg: "Directory is not empty"
    cmds:
      - git init
      - echo "# " >> README.md
      - echo "node_modules\ndist\n" >> .gitignore
      - rtx use task
      - task --init
      - mkdir apps
      - mkdir src
      - npm init -y
      - git add --all
      - git commit -m "Initial commit"
