# https://taskfile.dev

version: '3'

includes:
  project:
    taskfile: ~/configs/tasks/project.yml
    aliases: ["p"]

# output:
#   group:
#     error_only: true

tasks:

  default:
    desc: List all tasks with descriptions
    silent: true
    cmds:
      - task --list

  up:
    desc: Run docker compose up
    cmds:
      - docker compose up

  down:
    desc: Run docker compose down
    cmds:
      - docker compose down

  dev:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - npm run dev

  build:
    desc: Build project (can be wachted with the '-w' task flag)
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    sources:
      - src/**
    generates:
      - dist/**
    cmds:
      - npx vite build

  vite:
    desc: vite dev
    silent: true
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - npx vite -c vite.config.ts
