#!/bin/zsh
# mise hide=true

prompt="""
The logs for each project:

$(mise run book $1 $2)

--------------------------------------------------------------------------------

Write me a summary of work to put in my work jurnal with the following guidelines:

- Write it as a unordered list, with every entry in short, plain english sentences.
- Combine duplicate and similar log entries into one.
- A maximum of 5 entries per day.
- Ignore log entires with 'Merge'.
- Ignore lockfile changes.
"""

# echo $prompt
ollama run llama3.2 "$prompt"
