#!/bin/bash
# mise hide=true

prompt="Write me a summary of work to put in my work record. Write it as a 1 level deep list, Ignore all commits with "Merge" nane. Keep it short and simple. Maximum of 5 entries."

book $1 $2 | mods $prompt
