#!/bin/zsh
# mise hide=true

prompt='Write me a summary of work to put in my work record. Write it as a 1 level deep list, Ignore all commits with "Merge" nane. Keep it short and simple. Maximum of 5 entries.'

log=$(mise run book $1 $2)

ollama run llama3.2 "$prompt\n$log"
