#!/bin/bash

# mise hide=true

project=$(find ~/source -maxdepth 2 -name .git -type d | sed 's/\/.git//g' | fzf --preview-window="30%" --preview="glow {}/README.md")

if [ -z "$project" ]; then
	echo "You need to select a project."
else
	cd $project
	id=$project

	zellij -s ${id//\//_} || zellij attach ${id//\//_}
fi
