#!/bin/bash

# mise hide=true

project=$(find ~/source -maxdepth 2 -name .git -type d | sed 's/\/.git//g' | gum filter --sort --reverse --header="Find Project")

if [ -z "$project" ]; then
	echo "You need to select a project."
else
	cd $project
	id=$project

	tmux new-session -d -s $id
	tmux send 'ls -la && git-stack' ENTER

	if [ -z "$TMUX" ]; then
		tmux attach -t $id
	else
		tmux switch-client -t $id
	fi
fi
