#!/bin/bash
# mise.hide=true

# https://gist.github.com/srsholmes/5607e26c187922878943c50edfb245ef
branches=$(git branch --sort=-committerdate --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(contents:subject) %(color:green)(%(committerdate:relative)) [%(authorname)]')
branch=$(echo "$branches" | gum filter)
git checkout $(echo "$branch" | tr -d "*" | awk '{print $1}')
