#!/bin/bash
# mise hide=true
# mise.description=Create a one time password from the kdbx database

source $CONFIGS_DIR/commands.sh

pw=$(security find-generic-password -ws "$KEY_DATABASE_URL")

if [ "$pw" != "" ]
then
    list=$(key --password="$pw" list)

    if [ "$list" != "" ]
    then
        name=$(echo "$list" | gum filter)
        key --password="$pw" otp "$name"
    fi
fi
