#!/bin/bash
# mise hide=true
# mise.description=Access a password from the kdbx database

pw=$(security find-generic-password -ws "Private.kdbx")

if [ "$pw" != "" ]
then
    list=$(key --password="$pw" list)

    if [ "$list" != "" ]
    then
        name=$(echo "$list" | gum filter)
        key --password="$pw" get "$name" | clip
    fi
fi
