#!/bin/bash
# mise hide=true

# mise alias="ta"

SESSION=$(tmux list-sessions -F \#S | gum filter --placeholder "Pick session...")
gum log --time rfc822 --prefix=tmux_attach --level info "Switching to $SESSION"
tmux switch-client -t $SESSION || tmux attach -t $SESSION
