#!/bin/zsh
#MISE description="Upload a file to public remote storage"
#MISE hide=true
#MISE dir="{{cwd}}"

#USAGE arg "<target>" help="The target to backup relative to the current directory"

rclone copyto --progress $usage_target storage:/pub/$usage_target

echo ""
echo "Upload complete"
echo "Link: https://storage.luckydye.de/pub/$usage_target"
echo ""
