# Inserts a blank line between shell prompts
add_newline = false

format = """
$username\
$hostname\
$localip\
$env_var\
$cmd_duration\
$jobs\
$status\
$os\
$container\
$shell\
$battery\
$directory\
$character\
"""

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

[battery]
full_symbol = ''
charging_symbol = ''
discharging_symbol = ''

[[battery.display]]
threshold = 10
style = 'bold red'
