---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Install neovim
      command: brew install neovim
      
    - name: Install neovim config
      command: ln -s $CONFIGS_DIR/.config/nvim ~/.config/
