---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost
  tasks:

    - name: Ping host
      delegate_to: localhost
      raw: bash
