# yaml-language-server: $schema=https://my.url.to/the/schema
- name: Setup enviroment

  groups:
    - all

  defaults:
    home_dir: "/Users/tihav"
    configs_dir: "/Users/tihav/source/configs"

  tasks:
    - !facts
    - !echo
      msg: "OS Flavor = {{ jet_os_flavor }}"

    # install dependencies
    - !echo
      msg: "Installing dependencies"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install stow ripgrep unzip fd fzf tmux
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: sudo apt update -y
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: sudo apt install -y stow git unzip fd-find fzf ripgrep zsh tmux build-essential

    # link configs

    - !template
      src: "{{ configs_dir }}/git/.gitconfig"
      dest: "{{ home_dir }}/.gitconfig"

    - !template
      src: "{{ configs_dir }}/rtx/config.toml"
      dest: "{{ home_dir }}/.config/rtx/config.toml"

    - !template
      src: "{{ configs_dir }}/task/Taskfile.yml"
      dest: "{{ home_dir }}/Taskfile.yml"

    - !template
      src: "{{ configs_dir }}/tmux/.tmux.conf"
      dest: "{{ home_dir }}/.tmux.conf"

    # I need symlinks!

    # - name: Link neovim config
    #   file:
    #     src: "{{ lookup('env', 'CONFIGS_DIR') }}/nvim"
    #     dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
    #     state: link

    # - name: Link vscode config
    #   file:
    #     src: "{{ lookup('env', 'CONFIGS_DIR') }}/vscode/settings.json"
    #     dest: "{{ lookup('env', 'HOME') }}/Library/Application\ Support/Code/User/settings.json"
    #     state: link

    # - name: Link vscode keybinds
    #   file:
    #     src: "{{ lookup('env', 'CONFIGS_DIR') }}/vscode/keybindings.json"
    #     dest: "{{ lookup('env', 'HOME') }}/Library/Application\ Support/Code/User/keybindings.json"
    #     state: link

    # - name: Link zed config
    #   file:
    #     src: "{{ lookup('env', 'CONFIGS_DIR') }}/zed/settings.json"
    #     dest: "{{ lookup('env', 'HOME') }}/.config/zed/settings.json"
    #     state: link

    # - name: Link zed keybinds
    #   file:
    #     src: "{{ lookup('env', 'CONFIGS_DIR') }}/zed/keymap.json"
    #     dest: "{{ lookup('env', 'HOME') }}/.config/zed/keymap.json"
    #     state: link

    # #
    #

    # install/update git
    - !echo
      msg: "Installing git"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install git
    - !apt
      with:
        condition: (eq jet_os_flavor "Debian")
      package: git

    # install/update rtx
    - !echo
      msg: "Installing rtx"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install rtx
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: curl -sL https://rtx.pub/install.sh -o ~/install_rtx.sh && \
            bash ~/install_rtx.sh && \
            rm ~/install_rtx.sh

    # install/update neovim
    - !echo
      msg: "Installing neovim"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install neovim
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: mkdir -p $HOME/bin && cd $HOME/bin && \
            sudo apt install -y libfuse2 && \
            curl -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o ~/bin//nvim && \
            chmod u+x ~/bin/nvim

    # install/update starship
    - !echo
      msg: "Installing starship"
    - !shell
      cmd: curl -sS https://starship.rs/install.sh | sh
