---
- name: Setup Mac Environment
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Install git config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/.gitconfig $HOME/.gitconfig

    - name: Install rtx config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/rtx $HOME/.config/

    - name: Install neovim config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/nvim $HOME/.config/

    - name: Install vscode config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/vscode/settings.json $HOME/Library/Application\ Support/Code/User/settings.json

    - name: Install vscode keybinds
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/vscode/keybindings.json $HOME/Library/Application\ Support/Code/User/keybindings.json

    - name: Install global Taskfile
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/tasks/Taskfile.yml $HOME/Taskfile.yml

    - name: Install git
      command: brew install git

    - name: Install RTX
      command: brew install rtx

    - name: Install neovim
      command: brew install neovim

    - name: Install navigation stuff
      command: brew install fd fzf tmux

    - name: Install tmux config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/.tmux.conf $HOME/.tmux.conf
