---

- name: Setup Ubuntu Machine
  connection: ansible.netcommon.network_cli
  gather_facts: true
  hosts: localhost
  tasks:
    - name: Update
      command: sudo apt update -y

    - name: Create source directory
      command: mkdir -p $HOME/source
      
    - name: Install apt packages
      ignore_errors: true
      command: sudo apt install git unzip fd-find fzf ripgrep tmux build-essential -y

    - name: Install git config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/.gitconfig $HOME/.gitconfig
      
    - name: Install ansible config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/.ansible.cfg $HOME/.ansible.cfg
      
    - name: Install neovim
      ignore_errors: true
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/bin && cd $HOME/bin
        - sudo apt install -y libfuse2
        - curl -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o ~/bin//nvim
        - chmod u+x ~/bin//nvim
      
    - name: Install neovim config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/nvim ~/.config/

    - name: Install Tools config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/rtx $HOME/.config/

    - name: Install rtx-cli
      ignore_errors: true
      command: "{{ item }}"
      with_items:
        - curl -sL https://rtx.pub/install.sh | RTX_INSTALL_PATH=~/bin/rtx sh
        - echo 'eval "$(rtx activate)"' >> ~/.bashrc
      
    - name: Install Tools
      ignore_errors: true
      command: "{{ item }}"
      with_items:
        - rtx install

    - name: Install global Taskfile
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/tasks/Taskfile.yml $HOME/Taskfile.yml
      
    - name: Install tmux config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/.tmux.conf $HOME/.tmux.conf

    - name: Link skate
      command: run skate_link
    
        
