# yaml-language-server: $schema=https://my.url.to/the/schema
- name: Setup enviroment

  groups:
    - all

  tasks:
    - !facts
    - !echo
      msg: "OS Flavor = {{ jet_os_flavor }}"

    # install dependencies
    - !echo
      msg: "Installing dependencies"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install stow ripgrep unzip fd fzf tmux
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: sudo apt update -y
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: sudo apt install -y stow git unzip fd-find fzf ripgrep zsh tmux build-essential

    # link configs
    - !shell
      cmd: sudo stow --ignore=".DS_Store" --target $HOME --dir $CONFIGS_DIR -R nvim git rtx tmux starship task vscode zed ansible

    # install/update git
    - !echo
      msg: "Installing git"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install git
    - !apt
      with:
        condition: (eq jet_os_flavor "Debian")
      package: git

    # install/update rtx
    - !echo
      msg: "Installing rtx"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install rtx
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: curl -sL https://rtx.pub/install.sh -o ~/install_rtx.sh && \
            bash ~/install_rtx.sh && \
            rm ~/install_rtx.sh

    # install/update neovim
    - !echo
      msg: "Installing neovim"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install neovim
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: mkdir -p $HOME/bin && cd $HOME/bin && \
            sudo apt install -y libfuse2 && \
            curl -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o ~/bin//nvim && \
            chmod u+x ~/bin/nvim

    # install/update starship
    - !echo
      msg: "Installing starship"
    - !shell
      with:
        condition: (eq jet_os_flavor "OSX")
      cmd: brew install starship
    - !shell
      with:
        condition: (eq jet_os_flavor "Debian")
      cmd: curl -sS https://starship.rs/install.sh | sh
