---
- name: Setup Ubuntu Enviroment
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Update
      command: sudo apt update -y

    - name: Create source directory
      command: mkdir -p $HOME/source

    - name: Install apt packages
      command: sudo apt install git unzip fd-find fzf ripgrep tmux build-essential -y

    - name: Install neovim
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/bin && cd $HOME/bin
        - sudo apt install -y libfuse2
        - curl -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o ~/bin//nvim
        - chmod u+x ~/bin//nvim

    - name: Install rtx-cli
      command: "{{ item }}"
      with_items:
        - curl -sL https://rtx.pub/install.sh -o install_rtx.sh
        - bash install_rtx.sh
        - echo 'eval "$(rtx activate)"' >> ~/.bashrc
        
    - name: Install git config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/.gitconfig"
        dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
        force: true
        state: link

    - name: Install rtx config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/rtx"
        dest: "{{ lookup('env', 'HOME') }}/.config/rtx"
        force: true
        state: link

    - name: Install neovim config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/nvim"
        dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
        force: true
        state: link

    - name: Install global Taskfile
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/tasks/Taskfile.yml"
        dest: "{{ lookup('env', 'HOME') }}/Taskfile.yml"
        force: true
        state: link

    - name: Install tmux config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/.tmux.conf"
        dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        force: true
        state: link

    - name: Install ansible config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/.ansible.cfg"
        dest: "{{ lookup('env', 'HOME') }}/.ansible.cfg"
        force: true
        state: link

    - name: Install Tools
      command: "{{ item }}"
      with_items:
        - ~/bin/rtx install -y
        
