---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Update
      command: sudo apt update -y

    - name: Create source directory
      command: mkdir -p $HOME/source
      
    - name: Install apt packages
      ignore_errors: true
      command: sudo apt install git unzip fd-find fzf ripgrep tmux build-essential -y

    - name: Install git config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/.gitconfig $HOME/.gitconfig
      
    - name: Install neovim
      ignore_errors: true
      command: "{{ item }}"
      with_items:
        - mkdir -p $HOME/bin && cd $HOME/bin
        - curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        - chmod u+x nvim.appimage
        - mv nvim.appImage nvim
      
    - name: Install neovim config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/nvim ~/.config/

    - name: Install rtx-cli
      ignore_errors: true
      command: "{{ item }}"
      with_items:
        - curl https://rtx.pub/install.sh | bash
        - echo 'eval "$(rtx activate)"' >> ~/.bashrc
        
    - name: Install Tools config
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/.config/rtx $HOME/.config/
      
    - name: Install Tools
      ignore_errors: true
      command: "{{ item }}"
      with_items:
        - rtx install

    - name: Install global Taskfile
      ignore_errors: true
      command: ln -s $CONFIGS_DIR/tasks/Taskfile.yml $HOME/Taskfile.yml
        
