---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Install Build dependencies
      command: sudo apt install build-essential -y

    - name: Install Cargo
      command: curl https://sh.rustup.rs -sSf > /tmp/rustup-init.sh

    - name: Install Cargo
      command: chmod 700 /tmp/rustup-init.sh && /tmp/rustup-init.sh -y
      
    - name: Install rtx-cli
      command: cargo install cargo-binstall && cargo binstall rtx-cli
      
    - name: Activate rtx-cli
      command: echo 'eval "$(rtx activate bash)"' >> ~/.bashrc
      
    - name: Install Node
      command: rtx install node@latest && rtx use --global node@latest
      
      
