---

- name: Network Getting Started First Playbook
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Install Build dependencies
      command: sudo apt install build-essential -y

    - name: Install Rust
      command: "{{ item }}"
      with_items:
        - curl https://sh.rustup.rs -sSf -o /tmp/rustup-init.sh
        - chmod 700 /tmp/rustup-init.sh
        - bash /tmp/rustup-init.sh -y
      
    - name: Install rtx-cli
      command: "{{ item }}"
      with_items:
        - cargo install cargo-binstall
        - cargo binstall rtx-cli
      
    - name: Activate rtx-cli
      command: echo 'eval "$(rtx activate bash)"' >> ~/.bashrc
      
    - name: Install Node
      command: "{{ item }}"
      with_items:
        - rtx install node@latest
        - rtx use --global node@latest
        
