---
- name: Setup Mac Environment
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Install git config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/.gitconfig"
        dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
        state: link

    - name: Install rtx config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/rtx"
        dest: "{{ lookup('env', 'HOME') }}/.config/rtx"
        state: link

    - name: Install neovim config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/nvim"
        dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
        state: link

    - name: Install vscode config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/vscode/settings.json"
        dest: "{{ lookup('env', 'HOME') }}/Library/Application\ Support/Code/User/settings.json"
        state: link

    - name: Install vscode keybinds
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/vscode/keybindings.json"
        dest: "{{ lookup('env', 'HOME') }}/Library/Application\ Support/Code/User/keybindings.json"
        state: link

    - name: Install zed config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/zed/settings.json"
        dest: "{{ lookup('env', 'HOME') }}/.config/zed/settings.json"
        state: link

    - name: Install zed keybinds
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/zed/keymap.json"
        dest: "{{ lookup('env', 'HOME') }}/.config/zed/keymap.json"
        state: link

    - name: Install global Taskfile
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/tasks/Taskfile.yml"
        dest: "{{ lookup('env', 'HOME') }}/Taskfile.yml"
        state: link

    - name: Install tmux config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/.tmux.conf"
        dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        state: link

    - name: Install ansible config
      file:
        src: "{{ lookup('env', 'CONFIGS_DIR') }}/.ansible.cfg"
        dest: "{{ lookup('env', 'HOME') }}/.ansible.cfg"
        state: link

    - name: Install git
      command: brew install git

    - name: Install RTX
      command: brew install rtx

    - name: Install neovim
      command: brew install neovim

    - name: Install navigation stuff
      command: brew install fd fzf tmux
