name: Ubuntu Setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run setup
        run: |
          curl https://raw.githubusercontent.com/luckydye/configs/main/setup.sh | bash
          source ~/.bashrc
          export PATH=$PATH:~/bin
          ls ~/bin
          rtx -v
          gum -v 
          skate -v
          nvim -v
